<a href="https://colab.research.google.com/github/baubyte/CienciaDeDatos/blob/main/Introducci%C3%B3n_a_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a Pandas

## Modulo 2

---

## Objetivo

Comprender cómo utilizar **Pandas** para manipular y analizar datasets.

## ¿Qué es Pandas?

Pandas es una librería especializada en:

- manipulación de datos
- análisis de datasets
- limpieza de información
- transformación de datos


Su estructura principal es el **DataFrame**, que funciona como una tabla similar a una hoja de cálculo o una tabla de base de datos.

Un DataFrame tiene:

filas → registros

columnas → variables

IMPORTACIÓN

In [ ]:

import pandas as pd

pd.set_option('display.float_format', '{:.2f}'.format)

## Crear un DataFrame
Un DataFrame puede construirse a partir de diferentes fuentes:

- diccionarios
- archivos CSV
- bases de datos
- APIs

En este ejemplo crearemos uno manualmente.

In [ ]:
datos = {
    "Nombre": ["Ana", "Juan", "María", "Pedro", "Laura"],
    "Edad": [25, 30, 22, 40, 28],
    "Ventas": [200, 150, 300, 250, 180],
    "Ciudad": ["Madrid", "Buenos Aires", "Madrid", "Bogotá", "Buenos Aires"]
}

df = pd.DataFrame(datos)

df

  Nombre  Edad  Ventas        Ciudad
0    Ana    25     200        Madrid
1   Juan    30     150  Buenos Aires
2  María    22     300        Madrid
3  Pedro    40     250        Bogotá
4  Laura    28     180  Buenos Aires

## Exploración inicial de datos

Cuando trabajamos con un dataset lo primero que debemos hacer es **explorar su estructura**.

In [ ]:
##Muestra las primeras filas.
df.head(3)

  Nombre  Edad  Ventas        Ciudad
0    Ana    25     200        Madrid
1   Juan    30     150  Buenos Aires
2  María    22     300        Madrid

In [ ]:
#Muestra las últimas filas.
df.tail(2)

  Nombre  Edad  Ventas        Ciudad
3  Pedro    40     250        Bogotá
4  Laura    28     180  Buenos Aires

In [ ]:
#(filas, columnas)
df.shape

(5, 4)

Permite ver:

- tipos de datos

- valores nulos

- estructura general

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  5 non-null      object
 1   Edad    5 non-null      int64
 2   Ventas  5 non-null      int64
 3   Ciudad  5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [ ]:
# Genera estadísticas descriptivas para variables numéricas.
df.describe()

       Edad  Ventas
count  5.00    5.00
mean  29.00  216.00
std    6.86   59.41
min   22.00  150.00
25%   25.00  180.00
50%   28.00  200.00
75%   30.00  250.00
max   40.00  300.00

## SELECCIONAR COLUMNAS

In [ ]:
df["Edad"]

0    25
1    30
2    22
3    40
4    28
Name: Edad, dtype: int64

In [ ]:
#Seleccionar múltiples columnas:
df[["Nombre","Ventas"]]

  Nombre  Ventas
0    Ana     200
1   Juan     150
2  María     300
3  Pedro     250
4  Laura     180

## FILTRAR DATOS
En Ciencia de Datos es común seleccionar registros que cumplen ciertas condiciones.

In [ ]:
#devuelve solo las filas que cumplen la condición
df[df["Edad"] > 25]

  Nombre  Edad  Ventas        Ciudad
1   Juan    30     150  Buenos Aires
3  Pedro    40     250        Bogotá
4  Laura    28     180  Buenos Aires

In [ ]:
#Filtrar por texto:
df[df["Ciudad"] == "Madrid"]

  Nombre  Edad  Ventas  Ciudad
0    Ana    25     200  Madrid
2  María    22     300  Madrid

## FILTROS MÚLTIPLES
Filtrado con múltiples condiciones

Utilizando operador & (AND):

In [ ]:
df[(df["Edad"] > 25) & (df["Ventas"] > 180)]

  Nombre  Edad  Ventas  Ciudad
3  Pedro    40     250  Bogotá

Utilizando operador | (OR):

In [ ]:
df[(df["Ciudad"] == "Madrid") | (df["Ciudad"] == "Bogotá")]

  Nombre  Edad  Ventas  Ciudad
0    Ana    25     200  Madrid
2  María    22     300  Madrid
3  Pedro    40     250  Bogotá

## OPERACIONES MATEMÁTICAS

In [ ]:
df["Edad"]

0    25
1    30
2    22
3    40
4    28
Name: Edad, dtype: int64

In [ ]:
# promedio de valores
df["Edad"].mean()

np.float64(29.0)

In [ ]:
# minimo
df["Edad"].min()

22

In [ ]:
# suma de todos los valores
total_edades = df["Edad"].sum()
total_edades

np.int64(145)

In [ ]:
# multiplicaciones
df["Edad"] * 100

0    2500
1    3000
2    2200
3    4000
4    2800
Name: Edad, dtype: int64

## INDEXACIÓN

### Indexación con LOC
 Permite seleccionar datos utilizando **etiquetas** (nombres de filas y columnas).

In [ ]:
#Seleccionar fila
df.loc[2]

Nombre     María
Edad          22
Ventas       300
Ciudad    Madrid
Name: 2, dtype: object

In [ ]:
#Seleccionar fila y columna:
df.loc[2, "Nombre"]

'María'

In [ ]:
# Seleccionar varias columnas:
df.loc[:, ["Nombre","Ventas"]]

  Nombre  Ventas
0    Ana     200
1   Juan     150
2  María     300
3  Pedro     250
4  Laura     180

: significa todas las filas

###INDEXACIÓN CON ILOC
`iloc` permite seleccionar datos utilizando **posiciones numéricas**.

primer número → filas

segundo número → columnas

In [ ]:
#Seleccionar fila por posición:
df.iloc[2]

Nombre     María
Edad          22
Ventas       300
Ciudad    Madrid
Name: 2, dtype: object

In [ ]:
#Seleccionar fila y columna:
df.iloc[2,1]

np.int64(22)

In [ ]:
#Seleccionar rango:
df.iloc[1:4]

  Nombre  Edad  Ventas        Ciudad
1   Juan    30     150  Buenos Aires
2  María    22     300        Madrid
3  Pedro    40     250        Bogotá

In [ ]:
#Seleccionar filas y columnas específicas:
df.iloc[0:3, 1:3]

   Edad  Ventas
0    25     200
1    30     150
2    22     300

## CREAR NUEVAS COLUMNAS
En análisis de datos muchas veces necesitamos generar nuevas variables.

In [ ]:
df["Ventas_con_impuesto"] = df["Ventas"] * 1.21

df

  Nombre  Edad  Ventas        Ciudad  Ventas_con_impuesto
0    Ana    25     200        Madrid               242.00
1   Juan    30     150  Buenos Aires               181.50
2  María    22     300        Madrid               363.00
3  Pedro    40     250        Bogotá               302.50
4  Laura    28     180  Buenos Aires               217.80

## ORDENAR DATOS

In [ ]:
# Ordenar por ventas:
df.sort_values("Ventas")

  Nombre  Edad  Ventas        Ciudad  Ventas_con_impuesto
1   Juan    30     150  Buenos Aires               181.50
4  Laura    28     180  Buenos Aires               217.80
0    Ana    25     200        Madrid               242.00
3  Pedro    40     250        Bogotá               302.50
2  María    22     300        Madrid               363.00

In [ ]:
# Orden descendente:
df.sort_values("Ventas", ascending=False)

  Nombre  Edad  Ventas        Ciudad  Ventas_con_impuesto
2  María    22     300        Madrid               363.00
3  Pedro    40     250        Bogotá               302.50
0    Ana    25     200        Madrid               242.00
4  Laura    28     180  Buenos Aires               217.80
1   Juan    30     150  Buenos Aires               181.50

## AGRUPACIÓN

Una operación muy utilizada en Ciencia de Datos es agrupar información por categorías.

Calcula el promedio de ventas por ciudad.

In [ ]:
df.groupby("Ciudad")["Ventas"].mean()

Ciudad
Bogotá         250.00
Buenos Aires   165.00
Madrid         250.00
Name: Ventas, dtype: float64

Calcula la suma de ventas por ciudad

In [ ]:
df.groupby("Ciudad")["Ventas"].sum()

Ciudad
Bogotá          250
Buenos Aires    330
Madrid          500
Name: Ventas, dtype: int64