<a href="https://colab.research.google.com/github/baubyte/CienciaDeDatos/blob/main/UNIDAD_II_pildora_merge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UNIDAD II-Píldora – Combinar datos con pandas (merge)

## ¿Cómo unimos información de distintas tablas?

Importamos las dependencias

In [ ]:
import pandas as pd

## EJEMPLO

Tenemos dos tablas:

- ventas
- productos

Queremos agregar información de productos a las ventas.

In [ ]:
ventas = pd.DataFrame({
    "producto_id": [1, 2, 3, 4],
    "ventas": [100, 200, 150, 300]
})

productos = pd.DataFrame({
    "producto_id": [1, 2, 3],
    "nombre": ["A", "B", "C"]
})

ventas, productos

(   producto_id  ventas
 0            1     100
 1            2     200
 2            3     150
 3            4     300,
    producto_id nombre
 0            1      A
 1            2      B
 2            3      C)

Cuando queremos combinar información entre tablas usamos `merge`, permite combinar información entre tablas usando una clave en común

## Merge básico

In [ ]:
pd.merge(ventas, productos, on='producto_id')

   producto_id  ventas nombre
0            1     100      A
1            2     200      B
2            3     150      C

Solo aparecen los registros que coinciden en ambas tablas

## Left join

Mantiene todas las ventas

In [ ]:
pd.merge(ventas, productos, on='producto_id', how='left')

   producto_id  ventas nombre
0            1     100      A
1            2     200      B
2            3     150      C
3            4     300    NaN

## Right join

Mantiene todos los productos

In [ ]:
pd.merge(ventas, productos, on='producto_id', how='right')

   producto_id  ventas nombre
0            1     100      A
1            2     200      B
2            3     150      C

¿Por qué en el right join no aparece el producto 4?

Porque ese producto no existe en la tabla de productos. Right join mantiene lo que existe en la tabla derecha.

Los joins no crean datos nuevos, Solo combinan los que ya existen

## Outer join

Mantiene todo de ambas tablas

In [ ]:
pd.merge(ventas, productos, on='producto_id', how='outer')

   producto_id  ventas nombre
0            1     100      A
1            2     200      B
2            3     150      C
3            4     300    NaN

## Importancia de la clave

Si la clave está mal definida, el resultado también será incorrecto

## Conclusión

`merge` sirve para combinar información.

No apila datos (eso lo hacía concat)
Relaciona tablas mediante una clave