<a href="https://colab.research.google.com/github/baubyte/CienciaDeDatos/blob/main/UNIDAD_II_AGRUPACION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UNIDAD II - AGRUPACIÓN

Tenemos un dataset y queremos empezar a analizarlo.

Antes de aplicar técnicas más complejas, necesitamos entender los datos.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "categoria": ["A", "A", "B", "B", "C", "C", "A"],
    "sucursal": ["Norte", "Sur", "Norte", "Sur", "Norte", "Sur", "Norte"],
    "ventas": [100, 150, 200, 120, 300, 180, 90]
})

df

  categoria sucursal  ventas
0         A    Norte     100
1         A      Sur     150
2         B    Norte     200
3         B      Sur     120
4         C    Norte     300
5         C      Sur     180
6         A    Norte      90

### Valores únicos

In [ ]:
df['categoria'].unique()

array(['A', 'B', 'C'], dtype=object)

### Cantidad de valores distintos

In [ ]:
df['categoria'].nunique()

3

### Frecuencia de cada valor

In [ ]:
df['categoria'].value_counts()

categoria
A    3
B    2
C    2
Name: count, dtype: int64

### Ordenar resultados

In [ ]:
df['categoria'].value_counts().sort_values()

categoria
B    2
C    2
A    3
Name: count, dtype: int64

## Queremos ver patrones.

GroupBy permite agrupar datos y aplicar cálculos.

## Suma por categoría

In [ ]:
df.groupby('categoria')['ventas'].sum()

categoria
A    340
B    320
C    480
Name: ventas, dtype: int64

## Promedio por categoría

In [ ]:
df.groupby('categoria')['ventas'].mean()

categoria
A    113.333333
B    160.000000
C    240.000000
Name: ventas, dtype: float64

## Cantidad de registros

In [ ]:
df.groupby('categoria')['ventas'].count()

categoria
A    3
B    2
C    2
Name: ventas, dtype: int64

## Agrupar por múltiples variables

In [ ]:
df.groupby(['categoria','sucursal'])['ventas'].sum()

categoria  sucursal
A          Norte       190
           Sur         150
B          Norte       200
           Sur         120
C          Norte       300
           Sur         180
Name: ventas, dtype: int64

## Múltiples métricas

In [ ]:
df.groupby('categoria')['ventas'].agg(['sum','mean','count'])

           sum        mean  count
categoria
A          340  113.333333      3
B          320  160.000000      2
C          480  240.000000      2