<a href="https://colab.research.google.com/github/baubyte/CienciaDeDatos/blob/main/UNIDAD_II_pildora_concat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  UNIDAD II – Concatenación de datos con pandas

## ¿Cómo unimos datasets con la misma estructura?

Tenemos datos de ventas separados por meses.
Todos tienen la misma estructura.

¿Cómo los unimos en un solo dataset?

Importamos las dependencias

In [ ]:
import pandas as pd

In [ ]:
df_enero = pd.DataFrame({
    "producto": ["A", "B"],
    "ventas": [100, 200]
})

df_febrero = pd.DataFrame({
    "producto": ["A", "B"],
    "ventas": [150, 250]
})

df_enero, df_febrero

(  producto  ventas
 0        A     100
 1        B     200,
   producto  ventas
 0        A     150
 1        B     250)

Cuando los datasets tienen la misma estructura, podemos **apilarlos**.

Para eso usamos `pd.concat()`

## Concatenar por filas (caso más común)

Agregamos filas (stack vertical)

In [ ]:
pd.concat([df_enero, df_febrero])

  producto  ventas
0        A     100
1        B     200
0        A     150
1        B     250

## Resetear índice

Evita índices duplicados

In [ ]:
pd.concat([df_enero, df_febrero], ignore_index=True)

  producto  ventas
0        A     100
1        B     200
2        A     150
3        B     250

## Concatenar por columnas

Agregamos columnas (lado a lado)

In [ ]:
pd.concat([df_enero, df_febrero], axis=1)

  producto  ventas producto  ventas
0        A     100        A     150
1        B     200        B     250

## Agregar claves (identificar origen)

Permite saber de qué dataset viene cada fila

In [ ]:
pd.concat([df_enero, df_febrero], keys=['enero','febrero'])

          producto  ventas
enero   0        A     100
        1        B     200
febrero 0        A     150
        1        B     250

## Columnas diferentes

Si las columnas no coinciden, pandas completa con NaN

In [ ]:
df_marzo = pd.DataFrame({
    "producto": ["A", "B"],
    "ventas": [120, 220],
    "sucursal": ["X", "Y"]
})

pd.concat([df_enero, df_marzo], ignore_index=True)

  producto  ventas sucursal
0        A     100      NaN
1        B     200      NaN
2        A     120        X
3        B     220        Y

## Controlar columnas con join

- outer (default): todas las columnas
- inner: solo las comunes

In [ ]:
pd.concat([df_enero, df_marzo], join='outer', ignore_index=True)

  producto  ventas sucursal
0        A     100      NaN
1        B     200      NaN
2        A     120        X
3        B     220        Y

`concat` sirve para:

- juntar datasets iguales
- agregar filas o columnas

No combina información, solo la acumula